/*
 * Physio API
 *
 * Physio rehabilitation management API for Web-In-Cloud system
 *
 * API version: 1.0.0
 * Contact: xbukovska@stuba.sk
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package physio

import (
	"github.com/gin-gonic/gin"
)

type RehabilitationPlansAPI interface {


    // CreateRehabilitationPlan Post /api/rehabilitation-plans
    // Create rehabilitation plan 
     CreateRehabilitationPlan(c *gin.Context)

    // DeleteRehabilitationPlan Delete /api/rehabilitation-plans/:planId
    // Delete rehabilitation plan 
     DeleteRehabilitationPlan(c *gin.Context)

    // GetRehabilitationPlan Get /api/rehabilitation-plans/:planId
    // Get rehabilitation plan detail 
     GetRehabilitationPlan(c *gin.Context)

    // GetRehabilitationPlans Get /api/rehabilitation-plans
    // List rehabilitation plans 
     GetRehabilitationPlans(c *gin.Context)

    // UpdateRehabilitationPlan Put /api/rehabilitation-plans/:planId
    // Update rehabilitation plan 
     UpdateRehabilitationPlan(c *gin.Context)

}