/*
 * Physio API
 *
 * Physio rehabilitation management API for Web-In-Cloud system
 *
 * API version: 1.0.0
 * Contact: xbukovska@stuba.sk
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package physio

import (
	"github.com/gin-gonic/gin"
)

type PatientsAPI interface {


    // CreatePatient Post /api/patients
    // Create patient 
     CreatePatient(c *gin.Context)

    // DeletePatient Delete /api/patients/:patientId
    // Delete patient 
     DeletePatient(c *gin.Context)

    // GetPatient Get /api/patients/:patientId
    // Get patient detail 
     GetPatient(c *gin.Context)

    // GetPatients Get /api/patients
    // List patients 
     GetPatients(c *gin.Context)

    // UpdatePatient Put /api/patients/:patientId
    // Update patient 
     UpdatePatient(c *gin.Context)

}