/*
 * Physio API
 *
 * Physio rehabilitation management API for Web-In-Cloud system
 *
 * API version: 1.0.0
 * Contact: xbukovska@stuba.sk
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package physio

import (
	"github.com/gin-gonic/gin"
)

type RehabilitationSessionsAPI interface {


    // CreateRehabilitationSession Post /api/rehabilitation-sessions
    // Create rehabilitation session 
     CreateRehabilitationSession(c *gin.Context)

    // DeleteRehabilitationSession Delete /api/rehabilitation-sessions/:sessionId
    // Delete rehabilitation session 
     DeleteRehabilitationSession(c *gin.Context)

    // GetRehabilitationSession Get /api/rehabilitation-sessions/:sessionId
    // Get rehabilitation session detail 
     GetRehabilitationSession(c *gin.Context)

    // GetRehabilitationSessions Get /api/rehabilitation-sessions
    // List rehabilitation sessions 
     GetRehabilitationSessions(c *gin.Context)

    // UpdateRehabilitationSession Put /api/rehabilitation-sessions/:sessionId
    // Update rehabilitation session 
     UpdateRehabilitationSession(c *gin.Context)

}