/*
 * Physio API
 *
 * Physio rehabilitation management API for Web-In-Cloud system
 *
 * API version: 1.0.0
 * Contact: xbukovska@stuba.sk
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package physio

import (
	"github.com/gin-gonic/gin"
)

type TherapistsAPI interface {


    // CreateTherapist Post /api/therapists
    // Create therapist 
     CreateTherapist(c *gin.Context)

    // DeleteTherapist Delete /api/therapists/:therapistId
    // Delete therapist 
     DeleteTherapist(c *gin.Context)

    // GetTherapist Get /api/therapists/:therapistId
    // Get therapist detail 
     GetTherapist(c *gin.Context)

    // GetTherapists Get /api/therapists
    // List therapists 
     GetTherapists(c *gin.Context)

    // UpdateTherapist Put /api/therapists/:therapistId
    // Update therapist 
     UpdateTherapist(c *gin.Context)

}