/*
 * Physio API
 *
 * Physio rehabilitation management API for Web-In-Cloud system
 *
 * API version: 1.0.0
 * Contact: xbukovska@stuba.sk
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package physio

import (
	"github.com/gin-gonic/gin"
)

type AvailabilityAPI interface {


    // CheckAvailability Get /api/availability
    // Check ambulance and therapist availability 
     CheckAvailability(c *gin.Context)

}