/*
 * Physio API
 *
 * Physio rehabilitation management API for Web-In-Cloud system
 *
 * API version: 1.0.0
 * Contact: xbukovska@stuba.sk
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package physio

import (
	"github.com/gin-gonic/gin"
)

type AmbulancesAPI interface {


    // CreateAmbulance Post /api/ambulances
    // Create ambulance 
     CreateAmbulance(c *gin.Context)

    // DeleteAmbulance Delete /api/ambulances/:ambulanceId
    // Delete ambulance 
     DeleteAmbulance(c *gin.Context)

    // GetAmbulance Get /api/ambulances/:ambulanceId
    // Get ambulance detail 
     GetAmbulance(c *gin.Context)

    // GetAmbulances Get /api/ambulances
    // List ambulances 
     GetAmbulances(c *gin.Context)

    // UpdateAmbulance Put /api/ambulances/:ambulanceId
    // Update ambulance 
     UpdateAmbulance(c *gin.Context)

}