/*
 * Physio API
 *
 * Physio rehabilitation management API for Web-In-Cloud system
 *
 * API version: 1.0.0
 * Contact: xbukovska@stuba.sk
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package physio

type Ambulance struct {

	// Unique identifier of the ambulance or rehabilitation room
	Id string `json:"id"`

	Name string `json:"name"`

	RoomNumber string `json:"roomNumber"`

	Location string `json:"location,omitempty"`

	Notes string `json:"notes,omitempty"`
}
