/*
 * Physio API
 *
 * Physio rehabilitation management API for Web-In-Cloud system
 *
 * API version: 1.0.0
 * Contact: xbukovska@stuba.sk
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package physio

type AvailabilityCheckItem struct {

	ResourceId string `json:"resourceId,omitempty"`

	IsAvailable bool `json:"isAvailable"`

	ConflictingSessionId *string `json:"conflictingSessionId,omitempty"`
}
