/*
 * Physio API
 *
 * Physio rehabilitation management API for Web-In-Cloud system
 *
 * API version: 1.0.0
 * Contact: xbukovska@stuba.sk
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package physio

import (
	"time"
)

type RehabilitationSession struct {

	// Unique identifier of the session
	Id string `json:"id"`

	// Identifier of the parent rehabilitation plan
	PlanId string `json:"planId"`

	// Identifier of the ambulance or room where the session takes place
	AmbulanceId string `json:"ambulanceId"`

	// Identifier of the doctor or physiotherapist assigned to the session
	TherapistId string `json:"therapistId"`

	// Start of the session. May be null for tentative scheduling.
	StartDateTime *time.Time `json:"startDateTime,omitempty"`

	// End of the session. May be null for tentative scheduling.
	EndDateTime *time.Time `json:"endDateTime,omitempty"`

	AttendanceStatus AttendanceStatus `json:"attendanceStatus"`

	ConfirmationStatus SessionConfirmationStatus `json:"confirmationStatus"`

	SessionNotes string `json:"sessionNotes,omitempty"`
}
