/*
 * Physio API
 *
 * Physio rehabilitation management API for Web-In-Cloud system
 *
 * API version: 1.0.0
 * Contact: xbukovska@stuba.sk
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package physio

type Therapist struct {

	// Unique identifier of the therapist
	Id string `json:"id"`

	FirstName string `json:"firstName"`

	Surname string `json:"surname"`

	Title string `json:"title,omitempty"`

	Specialization string `json:"specialization,omitempty"`

	Email string `json:"email"`

	Phone string `json:"phone"`
}
