/*
 * Physio API
 *
 * Physio rehabilitation management API for Web-In-Cloud system
 *
 * API version: 1.0.0
 * Contact: xbukovska@stuba.sk
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package physio

type AttendanceStatus string

// List of AttendanceStatus
const (
	PLANNED AttendanceStatus = "planned"
	ATTENDED AttendanceStatus = "attended"
	CANCELED AttendanceStatus = "canceled"
)
