/*
 * Physio API
 *
 * Physio rehabilitation management API for Web-In-Cloud system
 *
 * API version: 1.0.0
 * Contact: xbukovska@stuba.sk
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package physio

type RehabilitationPlan struct {

	// Unique identifier of the rehabilitation plan
	Id string `json:"id"`

	// Identifier of the patient who owns the plan
	PatientId string `json:"patientId"`

	Status RehabilitationPlanStatus `json:"status"`

	Notes string `json:"notes,omitempty"`
}
