/*
 * Physio API
 *
 * Physio rehabilitation management API for Web-In-Cloud system
 *
 * API version: 1.0.0
 * Contact: xbukovska@stuba.sk
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package physio

type Patient struct {

	// Unique identifier of the patient
	Id string `json:"id"`

	FirstName string `json:"firstName"`

	Surname string `json:"surname"`

	// Rodne cislo pacienta
	BirthNumber string `json:"birthNumber"`

	DateOfBirth string `json:"dateOfBirth"`

	Sex Sex `json:"sex"`

	HealthInsurance HealthInsurance `json:"healthInsurance"`

	Email string `json:"email"`

	Phone string `json:"phone"`

	FirstVisitDate string `json:"firstVisitDate"`
}
