/*
 * Physio API
 *
 * Physio rehabilitation management API for Web-In-Cloud system
 *
 * API version: 1.0.0
 * Contact: xbukovska@stuba.sk
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package physio

type HealthInsurance string

// List of HealthInsurance
const (
	UNION HealthInsurance = "UNION"
	VSZP HealthInsurance = "VSZP"
	DOVERA HealthInsurance = "Dovera"
)
