/*
 * Physio API
 *
 * Physio rehabilitation management API for Web-In-Cloud system
 *
 * API version: 1.0.0
 * Contact: xbukovska@stuba.sk
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package physio

type SessionConfirmationStatus string

// List of SessionConfirmationStatus
const (
	TENTATIVE SessionConfirmationStatus = "tentative"
	CONFIRMED SessionConfirmationStatus = "confirmed"
)
