/*
 * Physio API
 *
 * Physio rehabilitation management API for Web-In-Cloud system
 *
 * API version: 1.0.0
 * Contact: xbukovska@stuba.sk
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package physio

type RehabilitationPlanStatus string

// List of RehabilitationPlanStatus
const (
	DRAFT         RehabilitationPlanStatus = "draft"
	ACTIVE        RehabilitationPlanStatus = "active"
	COMPLETED     RehabilitationPlanStatus = "completed"
	PLAN_CANCELED RehabilitationPlanStatus = "canceled"
)
