/*
 * Physio API
 *
 * Physio rehabilitation management API for Web-In-Cloud system
 *
 * API version: 1.0.0
 * Contact: xbukovska@stuba.sk
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package physio

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// Route is the information for every URI.
type Route struct {
	// Name is the name of this Route.
	Name		string
	// Method is the string for the HTTP method. ex) GET, POST etc..
	Method		string
	// Pattern is the pattern of the URI.
	Pattern	 	string
	// HandlerFunc is the handler function of this route.
	HandlerFunc	gin.HandlerFunc
}

// NewRouter returns a new router.
func NewRouter(handleFunctions ApiHandleFunctions) *gin.Engine {
	return NewRouterWithGinEngine(gin.Default(), handleFunctions)
}

// NewRouter add routes to existing gin engine.
func NewRouterWithGinEngine(router *gin.Engine, handleFunctions ApiHandleFunctions) *gin.Engine {
	for _, route := range getRoutes(handleFunctions) {
		if route.HandlerFunc == nil {
			route.HandlerFunc = DefaultHandleFunc
		}
		switch route.Method {
		case http.MethodGet:
			router.GET(route.Pattern, route.HandlerFunc)
		case http.MethodPost:
			router.POST(route.Pattern, route.HandlerFunc)
		case http.MethodPut:
			router.PUT(route.Pattern, route.HandlerFunc)
		case http.MethodPatch:
			router.PATCH(route.Pattern, route.HandlerFunc)
		case http.MethodDelete:
			router.DELETE(route.Pattern, route.HandlerFunc)
		}
	}

	return router
}

// Default handler for not yet implemented routes
func DefaultHandleFunc(c *gin.Context) {
	c.String(http.StatusNotImplemented, "501 not implemented")
}

type ApiHandleFunctions struct {

	// Routes for the AmbulancesAPI part of the API
	AmbulancesAPI AmbulancesAPI
	// Routes for the AvailabilityAPI part of the API
	AvailabilityAPI AvailabilityAPI
	// Routes for the PatientsAPI part of the API
	PatientsAPI PatientsAPI
	// Routes for the RehabilitationPlansAPI part of the API
	RehabilitationPlansAPI RehabilitationPlansAPI
	// Routes for the RehabilitationSessionsAPI part of the API
	RehabilitationSessionsAPI RehabilitationSessionsAPI
	// Routes for the TherapistsAPI part of the API
	TherapistsAPI TherapistsAPI
}

func getRoutes(handleFunctions ApiHandleFunctions) []Route {
	return []Route{ 
		{
			"CreateAmbulance",
			http.MethodPost,
			"/api/ambulances",
			handleFunctions.AmbulancesAPI.CreateAmbulance,
		},
		{
			"DeleteAmbulance",
			http.MethodDelete,
			"/api/ambulances/:ambulanceId",
			handleFunctions.AmbulancesAPI.DeleteAmbulance,
		},
		{
			"GetAmbulance",
			http.MethodGet,
			"/api/ambulances/:ambulanceId",
			handleFunctions.AmbulancesAPI.GetAmbulance,
		},
		{
			"GetAmbulances",
			http.MethodGet,
			"/api/ambulances",
			handleFunctions.AmbulancesAPI.GetAmbulances,
		},
		{
			"UpdateAmbulance",
			http.MethodPut,
			"/api/ambulances/:ambulanceId",
			handleFunctions.AmbulancesAPI.UpdateAmbulance,
		},
		{
			"CheckAvailability",
			http.MethodGet,
			"/api/availability",
			handleFunctions.AvailabilityAPI.CheckAvailability,
		},
		{
			"CreatePatient",
			http.MethodPost,
			"/api/patients",
			handleFunctions.PatientsAPI.CreatePatient,
		},
		{
			"DeletePatient",
			http.MethodDelete,
			"/api/patients/:patientId",
			handleFunctions.PatientsAPI.DeletePatient,
		},
		{
			"GetPatient",
			http.MethodGet,
			"/api/patients/:patientId",
			handleFunctions.PatientsAPI.GetPatient,
		},
		{
			"GetPatients",
			http.MethodGet,
			"/api/patients",
			handleFunctions.PatientsAPI.GetPatients,
		},
		{
			"UpdatePatient",
			http.MethodPut,
			"/api/patients/:patientId",
			handleFunctions.PatientsAPI.UpdatePatient,
		},
		{
			"CreateRehabilitationPlan",
			http.MethodPost,
			"/api/rehabilitation-plans",
			handleFunctions.RehabilitationPlansAPI.CreateRehabilitationPlan,
		},
		{
			"DeleteRehabilitationPlan",
			http.MethodDelete,
			"/api/rehabilitation-plans/:planId",
			handleFunctions.RehabilitationPlansAPI.DeleteRehabilitationPlan,
		},
		{
			"GetRehabilitationPlan",
			http.MethodGet,
			"/api/rehabilitation-plans/:planId",
			handleFunctions.RehabilitationPlansAPI.GetRehabilitationPlan,
		},
		{
			"GetRehabilitationPlans",
			http.MethodGet,
			"/api/rehabilitation-plans",
			handleFunctions.RehabilitationPlansAPI.GetRehabilitationPlans,
		},
		{
			"UpdateRehabilitationPlan",
			http.MethodPut,
			"/api/rehabilitation-plans/:planId",
			handleFunctions.RehabilitationPlansAPI.UpdateRehabilitationPlan,
		},
		{
			"CreateRehabilitationSession",
			http.MethodPost,
			"/api/rehabilitation-sessions",
			handleFunctions.RehabilitationSessionsAPI.CreateRehabilitationSession,
		},
		{
			"DeleteRehabilitationSession",
			http.MethodDelete,
			"/api/rehabilitation-sessions/:sessionId",
			handleFunctions.RehabilitationSessionsAPI.DeleteRehabilitationSession,
		},
		{
			"GetRehabilitationSession",
			http.MethodGet,
			"/api/rehabilitation-sessions/:sessionId",
			handleFunctions.RehabilitationSessionsAPI.GetRehabilitationSession,
		},
		{
			"GetRehabilitationSessions",
			http.MethodGet,
			"/api/rehabilitation-sessions",
			handleFunctions.RehabilitationSessionsAPI.GetRehabilitationSessions,
		},
		{
			"UpdateRehabilitationSession",
			http.MethodPut,
			"/api/rehabilitation-sessions/:sessionId",
			handleFunctions.RehabilitationSessionsAPI.UpdateRehabilitationSession,
		},
		{
			"CreateTherapist",
			http.MethodPost,
			"/api/therapists",
			handleFunctions.TherapistsAPI.CreateTherapist,
		},
		{
			"DeleteTherapist",
			http.MethodDelete,
			"/api/therapists/:therapistId",
			handleFunctions.TherapistsAPI.DeleteTherapist,
		},
		{
			"GetTherapist",
			http.MethodGet,
			"/api/therapists/:therapistId",
			handleFunctions.TherapistsAPI.GetTherapist,
		},
		{
			"GetTherapists",
			http.MethodGet,
			"/api/therapists",
			handleFunctions.TherapistsAPI.GetTherapists,
		},
		{
			"UpdateTherapist",
			http.MethodPut,
			"/api/therapists/:therapistId",
			handleFunctions.TherapistsAPI.UpdateTherapist,
		},
	}
}
